# Due to --uninstalled option passed to udisks
module_link:
	$(AM_V_at) if [ ! -L ../$(MODULE_SO) ]; then ln -r -s .libs/$(MODULE_SO) ..; fi

module_unlink:
	$(AM_V_at) if [ -L ../$(MODULE_SO) ]; then rm ../$(MODULE_SO); fi
