#!/bin/bash

function print_help()
{
    echo "Usage:"
    echo "  $(basename $0) [OPTION...]"
    echo
    echo "  -l, --with-libblockdev-part   Use libblockdev-part for partition manipulation"
    echo "  -p, --with-parted             Use parted for partition manipulation"
    echo "  -h, --help                    Print this message"
}

case "$1" in
    -h|--help)
        print_help
        exit 1
        ;;

    -l|--with-libblockdev-part)
        sed "s/@have_libblockdev_part_spec@/1/" storaged.spec.in > storaged.spec
        ;;

    -p|--with-parted|*)
        sed "s/@have_libblockdev_part_spec@/0/" storaged.spec.in > storaged.spec
        ;;
esac
