#!/bin/bash

DEVICE=$1
read CURPASS
read NEWPASS

if ! echo -e "$CURPASS\n$NEWPASS\n$NEWPASS\n" | /sbin/cryptsetup luksAddKey $DEVICE; then
    exit 1
fi

if ! echo -e "$CURPASS\n$NEWPASS\n" | /sbin/cryptsetup luksRemoveKey $DEVICE; then
    exit 1
fi

exit 0
